version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "4502:3306"
  app:
    build: ./bezkoder-app
    restart: "on-failure:5"
    env_file: ./.env
    environment:
      PORT: ${PORT_DB}
      DB_HOST: db
      DB_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
  python-app:
    build: .
    restart: "on-failure:5"
    volumes:
      - ./python_scripts:/app/python_scripts
    ports:
      - "4545:4545"  # Puerto 4545 en el host se mapea al puerto 4545 en el contenedor
volumes:
  db_data:
